name: Release CLI
on:
  push:
    tags:
      - '*'

jobs:
  lint:
    runs-on: macOS-latest
    steps:
      - uses: nexmoinc/neru-actions/go-lint@master
        with:
          git-username: ${{ secrets.USER_NAME }}
          git-access-token: ${{ secrets.ACCESS_TOKEN }}
          version: 1.21
          dir: ${{ env.PROJ_DIR }}

  unit-test:
    runs-on: macOS-latest
    steps:
      - uses: nexmoinc/neru-actions/go-test@master
        with:
          git-username: ${{ secrets.USER_NAME }}
          git-access-token: ${{ secrets.ACCESS_TOKEN }}
          version: 1.21
          dir: ${{ env.PROJ_DIR }}

  build:
    needs: [ unit-test ]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERT_P12_BASE64_ENCODED }}
          p12-password: ${{ secrets.APPLE_CERT_PASSWORD }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://sichan-vonage:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Store credentials
        run: |
          xcrun notarytool store-credentials --apple-id "devrel@vonage.com" --team-id 7F2B5ZSP8Q --password ${{ secrets.APPLE_DEV_ID_PASSWORD }} devrel

      - name: Cross compile binaries
        env:
          GO_LDFLAGS: "-s -w -X 'github.com/nexmoinc/vcr-cli/main.apiVersion=${{variables.apiVersion}}' -X 'github.com/nexmoinc/vcr-cli/main.version=${{github.ref_name}}' -X 'github.com/nexmoinc/vcr-cli/main.buildDate=${{github.event.repository.updated_at}}' -X 'github.com/nexmoinc/vcr-cli/main.commit=${{github.sha}}' -X 'github.com/nexmoinc/vcr-cli/main.releaseUrl=https://api.github.com/${{github.repository}}'"
        run: |
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "$GO_LDFLAGS" -o vcr_darwin_amd64 .
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -ldflags "$GO_LDFLAGS" -o vcr_darwin_arm64 .
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags "$GO_LDFLAGS" -o vcr_linux_arm64 .
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "$GO_LDFLAGS" -o vcr_linux_amd64 .
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "$GO_LDFLAGS" -o vcr_windows_amd64.exe .

      - name: Code sign darwin binaries
        run: |
          codesign --timestamp --options=runtime -s "Developer ID Application: Nexmo Inc. (7F2B5ZSP8Q)" -v ./vcr_darwin_amd64
          codesign --timestamp --options=runtime -s "Developer ID Application: Nexmo Inc. (7F2B5ZSP8Q)" -v ./vcr_darwin_arm64

      - name: Check code signing
        run: |
          codesign -vvv --deep --strict ./vcr_darwin_amd64
          codesign -vvv --deep --strict ./vcr_darwin_arm64

      - name: Zip darwin binaries
        run: |
          zip vcr_darwin_amd64.zip ./vcr_darwin_amd64
          zip vcr_darwin_arm64.zip ./vcr_darwin_arm64

      - name: Notarize darwin binaries
        run: |
          xcrun notarytool submit vcr_darwin_amd64.zip --keychain-profile "devrel" --wait
          xcrun notarytool submit vcr_darwin_arm64.zip --keychain-profile "devrel" --wait

      - name: Create Compressed Tar
        run: |
          mkdir bin
          tar czf bin/vcr_darwin_amd64.tar.gz ./vcr_darwin_amd64
          tar czf bin/vcr_darwin_arm64.tar.gz ./vcr_darwin_arm64
          tar czf bin/vcr_linux_arm64.tar.gz ./vcr_linux_arm64
          tar czf bin/vcr_linux_amd64.tar.gz ./vcr_linux_amd64
          tar czf bin/vcr_windows_amd64.tar.gz ./vcr_windows_amd64.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/vcr_darwin_amd64.tar.gz
            bin/vcr_darwin_arm64.tar.gz
            bin/vcr_linux_arm64.tar.gz
            bin/vcr_linux_amd64.tar.gz
            bin/vcr_windows_amd64.tar.gz
